import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>my first app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to My website <a href="https://github.com/discordmod217">:D</a>
        </h1>

        <p className={styles.description}>
          Completely original !!
        </p>
        <div>(right now, ive just linked weird stuff)</div>
        <div className={styles.grid}>
          <a href="https://github.com/discordmod217" className={styles.card}>
            <h2>about me &rarr;</h2>
          </a>

          <a href="https://youtu.be/8dVQ0813KVM" className={styles.card}>
            <h2>whatever this web is abouBLOGS &rarr;</h2>
            <p>original ideas under work</p>
          </a>

          <a
            href="http://matias.ma/nsfw/"
            className={styles.card}
          >
            <h2>random stuff &rarr;</h2>
          </a>
{/* 
          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a> */}
        </div>
      </main>

      <footer className={styles.footer}>
          Powered by me, just me.
          {/* <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span> */}
      </footer>
    </div>
  )
}
